FROM oven/bun:1
WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN bun install 

RUN bun run db:migrate

RUN bun install

EXPOSE 3000

CMD ["bun", "run", "start:web"]