FROM oven/bun:1
WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./apps/backend ./apps/backend

RUN bun install 

run bun run db:migrate


expose 8080

CMD ["bun", "run", "start:backend"]